/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adivinaq;

import java.applet.AudioClip;
import java.util.Random;
/**
 *
 * @author IlseDaniela
 */
public class Menu extends javax.swing.JFrame {

static int libre;
  
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);


                    AudioClip sonido;
                    sonido = java.applet.Applet.newAudioClip(getClass().getResource("/adivinaq/Sonido/juego.wav"));
                    sonido.play();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Menu1 = new javax.swing.JLabel();
        INCES = new javax.swing.JButton();
        CRU = new javax.swing.JButton();
        ESTAG = new javax.swing.JButton();
        salirm1 = new javax.swing.JButton();
        JUGAR = new javax.swing.JButton();
        Menu3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Menu1.setFont(new java.awt.Font("AR CHRISTY", 0, 36)); // NOI18N
        Menu1.setForeground(new java.awt.Color(51, 0, 51));
        Menu1.setText("¿?  ADIVINA QUIEN  ¿?");
        Menu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        INCES.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        INCES.setForeground(new java.awt.Color(51, 0, 51));
        INCES.setText("Iniciar Cesion");
        INCES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INCESActionPerformed(evt);
            }
        });

        CRU.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        CRU.setForeground(new java.awt.Color(0, 0, 51));
        CRU.setText("Crear Usuario");
        CRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRUActionPerformed(evt);
            }
        });

        ESTAG.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        ESTAG.setForeground(new java.awt.Color(51, 0, 51));
        ESTAG.setText("Estadisticas");
        ESTAG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESTAGActionPerformed(evt);
            }
        });

        salirm1.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        salirm1.setForeground(new java.awt.Color(0, 0, 51));
        salirm1.setText("Salir");
        salirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirm1ActionPerformed(evt);
            }
        });

        JUGAR.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        JUGAR.setForeground(new java.awt.Color(0, 0, 51));
        JUGAR.setText("Jugar modo libre");
        JUGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUGARActionPerformed(evt);
            }
        });

        Menu3.setFont(new java.awt.Font("Aparajita", 0, 14)); // NOI18N
        Menu3.setForeground(new java.awt.Color(51, 0, 0));
        Menu3.setText("*Si juegas modo libre tu puntaje no se guardara");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaq/IMAGENES/blue_game_padgame_azu_12424.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaq/IMAGENES/blue_user_client_person_12581.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaq/IMAGENES/bluecarddestinationuser_azul_tarjeta_dedestin_12437.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaq/IMAGENES/bluecalendar_azul_12604.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaq/IMAGENES/blue_arrow_left_12459.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(Menu3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Menu1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CRU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(INCES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ESTAG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JUGAR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salirm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu1)
                .addGap(1, 1, 1)
                .addComponent(Menu3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(JUGAR))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INCES)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CRU)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ESTAG)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salirm1)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INCESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INCESActionPerformed
       libre=0;
        IniciarC I=new IniciarC();
       I.setVisible(true);
       this.setVisible(false);
       
    }//GEN-LAST:event_INCESActionPerformed

    private void CRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRUActionPerformed
        libre=0;
        Rejistro r=new Rejistro();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CRUActionPerformed

    private void ESTAGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESTAGActionPerformed
           EstadisticaG EG=new EstadisticaG();
           EG.setVisible(true);
           this.setVisible(false);
          
       
    }//GEN-LAST:event_ESTAGActionPerformed

    private void salirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirm1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirm1ActionPerformed

    private void JUGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUGARActionPerformed
        libre=1; 
        MENU_3 M3=new MENU_3();
         M3.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_JUGARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CRU;
    private javax.swing.JButton ESTAG;
    private javax.swing.JButton INCES;
    private javax.swing.JButton JUGAR;
    private javax.swing.JLabel Menu1;
    private javax.swing.JLabel Menu3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salirm1;
    // End of variables declaration//GEN-END:variables

 
}
