/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adivinaq;

/**
 *
 * @author IlseDaniela
 */
public class Menu2 extends javax.swing.JFrame {

    
    String jugador[];
    
    /**
     * Creates new form Menu2
     */
    public Menu2() {
        initComponents();
        bienvenido.setText("Bienvenid@ "+IniciarC.usuario_adivina[0]);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu3 = new javax.swing.JLabel();
        Menu1 = new javax.swing.JLabel();
        Menu2 = new javax.swing.JPanel();
        jugar = new javax.swing.JButton();
        salirm2 = new javax.swing.JButton();
        estin = new javax.swing.JButton();
        bienvenido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        salirm1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        Menu3.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        Menu3.setForeground(new java.awt.Color(0, 51, 51));
        Menu3.setText("Jugador");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Menu1.setFont(new java.awt.Font("AR CHRISTY", 0, 36)); // NOI18N
        Menu1.setForeground(new java.awt.Color(51, 0, 51));
        Menu1.setText("¿?  ADIVINA QUIEN  ¿?");
        Menu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Menu2.setBackground(new java.awt.Color(204, 204, 255));

        jugar.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        jugar.setForeground(new java.awt.Color(0, 0, 51));
        jugar.setText("Jugar");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });

        salirm2.setBackground(new java.awt.Color(204, 204, 255));
        salirm2.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        salirm2.setForeground(new java.awt.Color(255, 102, 102));
        salirm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaq/IMAGENES/icons8_Multiply_32px.png"))); // NOI18N
        salirm2.setBorder(null);
        salirm2.setBorderPainted(false);
        salirm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirm2ActionPerformed(evt);
            }
        });

        estin.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        estin.setForeground(new java.awt.Color(51, 0, 51));
        estin.setText("Estadisticas");
        estin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estinActionPerformed(evt);
            }
        });

        bienvenido.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(51, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaq/IMAGENES/blue_game_padgame_azu_12424.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaq/IMAGENES/bluecalendar_azul_12604.png"))); // NOI18N

        salirm1.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        salirm1.setForeground(new java.awt.Color(0, 0, 51));
        salirm1.setText("Regresar");
        salirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirm1ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaq/IMAGENES/blue_arrow_left_12459.png"))); // NOI18N

        javax.swing.GroupLayout Menu2Layout = new javax.swing.GroupLayout(Menu2);
        Menu2.setLayout(Menu2Layout);
        Menu2Layout.setHorizontalGroup(
            Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(salirm2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Menu2Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salirm1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu2Layout.createSequentialGroup()
                            .addComponent(bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48))
                        .addGroup(Menu2Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(Menu2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(estin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(Menu2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        Menu2Layout.setVerticalGroup(
            Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu2Layout.createSequentialGroup()
                .addComponent(salirm2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estin)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(salirm1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(Menu1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Menu2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu1)
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Menu2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
       
        MENU_3 m3=new MENU_3();
         m3.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jugarActionPerformed

    private void estinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estinActionPerformed
       Estadisticas E= new Estadisticas();
       E.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_estinActionPerformed

    private void salirm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirm2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_salirm2ActionPerformed

    private void salirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirm1ActionPerformed
        Menu M=new Menu();
        M.setVisible(true);
        this.setVisible(false);
                                
        
    }//GEN-LAST:event_salirm1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Menu1;
    private javax.swing.JPanel Menu2;
    private javax.swing.JLabel Menu3;
    private javax.swing.JLabel bienvenido;
    public javax.swing.JButton estin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JButton jugar;
    private javax.swing.JButton salirm1;
    public javax.swing.JButton salirm2;
    // End of variables declaration//GEN-END:variables


}
